-record(source_file, {file, timestamp, parse_status}).
-record(variable, {id, context, subject, name, value, origin}).
-define(VAR_ID(Context, Subject, VariableName), {Context, Subject, VariableName}).